location: East US
resourceGroup: bitebudget-rg
type: Microsoft.App/containerApps
properties:
  environmentId: /subscriptions/0ee4d157-5405-4a09-bf25-b4a0581a1adb/resourceGroups/bitebudget-rg/providers/Microsoft.App/managedEnvironments/bitebudget-env
  configuration:
    activeRevisionsMode: Single
    ingress:
      external: true
      targetPort: 5000
      transport: auto
      traffic:
        - weight: 100
          latestRevision: true
    registries:
      - server: bitebudgetacr219.azurecr.io
        username: bitebudgetacr219
        passwordSecretRef: registry-password
    secrets:
      - name: registry-password
        value: IanQpyd8rbQIYWjLsJpI+KrxRCVjj3KgVhHIYptf2C+ACRDfvaFH
  template:
    containers:
      - image: bitebudgetacr219.azurecr.io/backend:latest
        name: bitebudget-backend
        resources:
          cpu: 0.25
          memory: 0.5Gi
        env:
          - name: FLASK_ENV
            value: production
          - name: DATABASE_URL
            value: sqlite:///app/data/bitebudget.db
    scale:
      minReplicas: 0
      maxReplicas: 10
