version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///bitebudget.db
    volumes:
      - ./backend:/app
      - ./backend/bitebudget.db:/app/bitebudget.db
    networks:
      - bitebudget-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - bitebudget-network
    depends_on:
      - backend

networks:
  bitebudget-network:
    driver: bridge
