location: East US
resourceGroup: bitebudget-rg
type: Microsoft.App/containerApps
properties:
  environmentId: /subscriptions/0ee4d157-5405-4a09-bf25-b4a0581a1adb/resourceGroups/bitebudget-rg/providers/Microsoft.App/managedEnvironments/bitebudget-env
  configuration:
    activeRevisionsMode: Single
    ingress:
      external: true
      targetPort: 3000
      transport: auto
      traffic:
        - weight: 100
          latestRevision: true
    registries:
      - server: bitebudgetacr219.azurecr.io
        username: bitebudgetacr219
        passwordSecretRef: registry-password
    secrets:
      - name: registry-password
        value: IanQpyd8rbQIYWjLsJpI+KrxRCVjj3KgVhHIYptf2C+ACRDfvaFH
  template:
    containers:
      - image: bitebudgetacr219.azurecr.io/frontend:latest
        name: bitebudget-frontend
        resources:
          cpu: 0.5
          memory: 1.0Gi
        env:
          - name: REACT_APP_API_BASE_URL
            value: https://bitebudget-backend.livelymoss-133f0f64.eastus.azurecontainerapps.io
          - name: GENERATE_SOURCEMAP
            value: "false"
          - name: CI
            value: "true"
    scale:
      minReplicas: 0
      maxReplicas: 10
