name: Cleanup Container Images

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        image: [backend, frontend]
    
    steps:
      - name: Delete old container images
        continue-on-error: true
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'ct-6282/bitebudgetv2/${{ matrix.image }}'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete untagged images
        continue-on-error: true
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'ct-6282/bitebudgetv2/${{ matrix.image }}'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: true
          token: ${{ secrets.GITHUB_TOKEN }}
